import type { Metadata } from "next";

import Link from "next/link";
import { Montserrat } from "next/font/google";
import { ReduxProvider } from "@/state/provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "weather-project-redux",
  description: "Generated by appncy",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`dark m-auto grid justify-center min-h-screen grid-rows-[auto,1fr,auto] bg-background px-4 antialiased ${montserrat.className}`}
      >
        <ReduxProvider>
          <header className="text-xl font-bold leading-[4rem]">
            <Link href="/">Weather App</Link>
          </header>
          <main className="py-8">{children}</main>
          <footer className="text-center leading-[4rem] opacity-70">
            Weather App © Made By Lucas Gotz Baliner
          </footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
